// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;
import ballerina/log;
import service1.service2;

listener http:Listener ep0 = new (9090);

service / on ep0 {
    # The average score of the catalog service2 is currently serving
    #
    # + return - The whole-number average score
    resource function get average\-score() returns AverageScoreResponse|error {
        service2:CatalogResponse catalogResponse = check service2Client->/catalog.get();
        service2:Record[] records = catalogResponse.records;
        log:printInfo("average score request handled", recordCount = records.length());
        int totalScore = 0;
        foreach service2:Record 'record in records {
            totalScore += 'record.score;
        }
        int average = totalScore / records.length();
        return {average: average};
    }

    # Catch-all for any path this contract does not serve
    #
    # + return - A structured 404 error body
    resource function 'default [string... path]() returns http:NotFound {
        Error notFoundError = {code: 404, message: "not found", description: "no resource is defined for this path"};
        return <http:NotFound>{body: notFoundError};
    }
}

public type AverageScoreResponse record {
    # sum of every record's score divided by the record count, remainder discarded
    int average;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};
