// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;
import ballerina/log;

listener http:Listener ep0 = new (9090);

service / on ep0 {
    # The catalog service2 is currently serving (full or empty)
    #
    # + return - The current catalog
    resource function get catalog() returns CatalogResponse {
        Record[] currentRecords = currentCatalog();
        log:printInfo("catalog request handled", recordCount = currentRecords.length());
        return {records: currentRecords};
    }

    # The catalog's current mode
    #
    # + return - The current mode
    resource function get operations/mode() returns ModeResponse {
        return {mode: getCurrentMode()};
    }

    # Switch the catalog between full mode and empty mode
    #
    # + return - returns can be any of following types
    # http:Ok (The mode was switched)
    # http:BadRequest (The requested mode is not valid)
    resource function put operations/mode(@http:Payload ModeRequest payload) returns ModeResponse|ErrorBadRequest {
        string requestedMode = payload.mode;
        if requestedMode != "full" && requestedMode != "empty" {
            Error invalidModeError = {
                code: 400,
                message: "invalid mode",
                description: string `mode must be 'full' or 'empty', got '${requestedMode}'`
            };
            ErrorBadRequest badRequest = {body: invalidModeError};
            return badRequest;
        }
        CatalogMode newMode = requestedMode == "full" ? "full" : "empty";
        setCurrentMode(newMode);
        return {mode: newMode};
    }
}

public type ModeRequest record {
    # the mode to switch the catalog to
    string mode;
};

public type CatalogResponse record {
    # every record in the catalog's current mode (empty in empty mode)
    Record[] records;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type Record record {
    # record identifier
    int id;
    # record name
    string name;
    # record score
    int score;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type ModeResponse record {
    # the catalog's mode
    "full"|"empty" mode;
};
